globals:
  datasetBaseUrl: http://localhost:8080/

middlewares:
  rewrite:
    module: trifid-core/middlewares/rewrite.js

  welcome:
    module: trifid-core/middlewares/view.js
    paths: /
    methods: GET
    config:
      path: views/welcome.hbs

  parameters:
    module: trifid-core/middlewares/view.js
    paths: /parameters
    methods: GET
    config:
      path: views/parameters.hbs

  entity-renderer:
    module: "@zazuko/trifid-renderer-entity"

  fetch-handler:
    module: trifid-handler-fetch
    config:
      url: https://raw.githubusercontent.com/zazuko/tbbt-ld/master/dist/tbbt.nt
      contentType: application/n-triples
      split: true
      cache: true
