globals:
  datasetBaseUrl: http://localhost:8080/
  endpoints:
    default:
      url: /query

template:
  title: The Big Bang Theory - Linked Data

plugins:
  welcome:
    module: trifid-core/plugins/view.js
    paths: /
    methods: GET
    config:
      path: views/welcome.hbs

  parameters:
    module: trifid-core/plugins/view.js
    paths:
      - /parameters
      - /parameters/
    methods: GET
    config:
      path: views/parameters.hbs

  yasgui:
    module: trifid-plugin-yasgui
    config:
      urlShortener: https://s.zazuko.com/api/v1/shorten

  graph-explorer:
    module: trifid-plugin-graph-explorer
    config:
      dataLabelProperty: <http://schema.org/name> | rdfs:label
      schemaLabelProperty: <http://schema.org/name> | rdfs:label

  spex:
    module: trifid-plugin-spex

  entity-renderer:
    module: "@zazuko/trifid-entity-renderer"

  fetch-handler:
    module: trifid-handler-fetch
    config:
      url: https://raw.githubusercontent.com/zazuko/tbbt-ld/master/dist/tbbt.nq
      contentType: application/n-quads
